# Generated by Django 3.2 on 2024-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='user', max_length=15),
        ),
    ]
